name: sqflrvrpd
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  flutter_secure_storage: ^10.2.0
  path: ^1.9.1
  riverpod_generator: ^4.0.3
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
